version: '3'
services:


#################################################################
#                             Spark                             #
#################################################################

  spark-master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 8.8.8.8
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
    #  - 8080:8080 # ui
    networks: 
      - spark
      - web
    volumes:
      - ./spark/config/master:/conf
      - ./spark/data:/tmp/data
    labels:
      traefik.enable: true
      traefik.frontend.rule: Host:spark.docker.localhost
      traefik.port: 8080

  spark-worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: 8.8.8.8
    networks:
      - spark
    depends_on: 
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./spark/config/worker:/conf
      - ./spark/data:/tmp/data

#################################################################
#                             Traeik                            #
#################################################################

  proxy-traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
    #  - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    networks:
      - web
    labels:
      # traefik.frontend.auth.basic.users: admin:$$apr1$$hJFP6Zo1$$mZqoJoCwZBrZScE5TJy9K0
      traefik.enable: true
      traefik.backend: traefik
      traefik.frontend.rule: Host:traefik.docker.localhost
      traefik.port: 8080


networks: 
  web:
    external: true
  spark:
    driver: bridge
